#!/usr/bin/env bash

PATH_TO_FILE="/home/ubuntu/example-file.txt"
IP="198.51.100.10"
USERNAME="ubuntu"
PATH_TO_SSH_KEY="/home/ubuntu/.ssh/id_rsa"


echo "Transferring file: $PATH_TO_FILE"
echo "To: $USERNAME@$IP:~/"
echo "Using SSH key: $PATH_TO_SSH_KEY"

scp -o StrictHostKeyChecking=no -i "$PATH_TO_SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP":~/

if [ $? -eq 0 ]; then
    echo "Transfer completed successfully."
else
    echo "Transfer failed."
    exit 1
fi
