#!/usr/bin/env bash
# Configures Nginx to redirect /redirect_me with a 301 status code

# Update packages and install Nginx
apt-get update
apt-get install -y nginx

# Configure Nginx with redirection
cat > /etc/nginx/sites-available/default <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF

# Restart Nginx to apply changes
service nginx restart