#!/usr/bin/env bash
# Configures port forwarding from 8080 to 80

# Enable IP forwarding
sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/' /etc/sysctl.conf
sysctl -p

# Configure UFW to allow port 8080
ufw allow 8080/tcp

# Set up port forwarding
ufw route allow proto tcp from any to any port 8080
iptables -t nat -A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80

# Make iptables rules persistent
apt-get install -y iptables-persistent
netfilter-persistent save